---
- name: Install Apache
  hosts: ec2instances

  tasks:
    - name: Install Apache
      yum:
        name: 
          - httpd
          - httpd-devel
        state: present
    # - name: Copy the file
    #   copy:
    #     src: "{{item.src}}"
    #     dest: "{{item.dest}}"
    #     owner: root
    #     group: root
    #     mode: 0644
    #   with_items:
    #     - src: httpd.conf
    #       dest: /etc/httpd/conf/httpd.conf
    #     - src: httpd-vhosts
    #       dest: /etc/httpd/conf/htttp-vhosts.conf
    - name: Make sure apache started on the boot
      service:
        name: httpd
        state: started
        enabled: true
    - name: Adding html page
      copy:
        src: index.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644
      # command: cp  /var/www/html/index.html
      
